/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Question;
import game.logic.Controller;
import gui.utils.QuestionsTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jelena Tabaš
 */
public class ChangeQuestion extends javax.swing.JFrame {

    /**
     * Creates new form ChangeQuestion
     */
    public ChangeQuestion() {
        initComponents();
    }

    ChangeQuestion(boolean b) {
        initComponents();
        fixForm(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblApprovedQuestions = new javax.swing.JTable();
        jBChangeQuestion = new javax.swing.JButton();
        jBDeleteQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblApprovedQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTblApprovedQuestions);

        jBChangeQuestion.setText("Izmeni");
        jBChangeQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangeQuestionActionPerformed(evt);
            }
        });

        jBDeleteQuestion.setText("Obrisi");
        jBDeleteQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDeleteQuestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBChangeQuestion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBChangeQuestion)
                    .addComponent(jBDeleteQuestion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBChangeQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangeQuestionActionPerformed
        Controller.getInstance().changeQuestions();
        JOptionPane.showMessageDialog(this, "Izmenjena pitanja su uspesno sacuvana");
    }//GEN-LAST:event_jBChangeQuestionActionPerformed

    private void jBDeleteQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteQuestionActionPerformed
        Question question = Controller.getInstance().getApprovedQuestions().get(jTblApprovedQuestions.getSelectedRow());
        Controller.getInstance().deleteQuestion(question);
        JOptionPane.showMessageDialog(this, "Sistem je obrisao izabrano pitanje");  
    }//GEN-LAST:event_jBDeleteQuestionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBChangeQuestion;
    private javax.swing.JButton jBDeleteQuestion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblApprovedQuestions;
    // End of variables declaration//GEN-END:variables

    private void fixForm(boolean b) {
        QuestionsTableModel qtm = new QuestionsTableModel();
        jTblApprovedQuestions.setModel(qtm);
        visibleButtons(b);
    }

    private void visibleButtons(boolean b) {
        jBChangeQuestion.setVisible(b);
        jBDeleteQuestion.setVisible(!b);
    }
}
